# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170313192522) do

  create_table "bruits", force: :cascade do |t|
    t.string   "volume"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "carotid_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.integer  "bruit_id"
    t.float    "pulseCarotidRight"
    t.float    "pulseCarotidLeft"
    t.float    "pulseTemporalRight"
    t.float    "pulseTemporalLeft"
    t.float    "pulseRadialRight"
    t.float    "pulseRadialLeft"
    t.float    "bruitsDisNeckRight"
    t.float    "bruitsDisNeckLeft"
    t.float    "bruitsMidNeckRight"
    t.float    "bruitsMidNeckLeft"
    t.float    "bruitsProxNeckRight"
    t.float    "bruitsProxNeckLeft"
    t.float    "bruitsSupraRight"
    t.float    "bruitsSupraLeft"
    t.float    "bruitsChestRight"
    t.float    "bruitsChestLeft"
    t.float    "vertebralReversalRight"
    t.float    "vertebralReversalLeft"
    t.float    "ophthalmicReversalRight"
    t.float    "ophthalmicReversalLeft"
    t.float    "dicaPSVRight"
    t.float    "dicaPSVLeft"
    t.float    "dicaEDVRight"
    t.float    "dicaEDVLeft"
    t.float    "micaPSVRight"
    t.float    "micaPSVLeft"
    t.float    "micaEDVRight"
    t.float    "micaEDVLeft"
    t.float    "picaPSVRight"
    t.float    "picaPSVLeft"
    t.float    "picaEDVRight"
    t.float    "picaEDVLeft"
    t.float    "ecaPSVRight"
    t.float    "ecaPSVLeft"
    t.float    "ecaEDVRight"
    t.float    "ecaEDVLeft"
    t.float    "dccaPSVRight"
    t.float    "dccaPSVLeft"
    t.float    "dccaEDVRight"
    t.float    "dccaEDVLeft"
    t.float    "pccaPSVRight"
    t.float    "pccaPSVLeft"
    t.float    "pccaEDVRight"
    t.float    "pccaEDVLeft"
    t.float    "vertebralPSVRight"
    t.float    "vertebralPSVLeft"
    t.float    "vertebralEDVRight"
    t.float    "vertebralEDVLeft"
    t.float    "subclavianPSVRight"
    t.float    "subclavianPSVLeft"
    t.float    "subclavianEDVRight"
    t.float    "subclavianEDVLeft"
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end

  add_index "carotid_forms", ["bruit_id"], name: "index_carotid_forms_on_bruit_id"
  add_index "carotid_forms", ["form_id"], name: "index_carotid_forms_on_form_id"

  create_table "forms", force: :cascade do |t|
    t.integer  "technologist_id"
    t.integer  "gender_id"
    t.integer  "age"
    t.string   "gender"
    t.float    "bpRight"
    t.float    "bpLeft"
    t.string   "history"
    t.string   "symptoms"
    t.string   "prelimResults"
    t.string   "patientResults"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "user_id"
  end

  add_index "forms", ["gender_id"], name: "index_forms_on_gender_id"
  add_index "forms", ["technologist_id"], name: "index_forms_on_technologist_id"
  add_index "forms", ["user_id"], name: "index_forms_on_user_id"

  create_table "genders", force: :cascade do |t|
    t.string   "gender"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "hepatic_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.boolean  "organEnlarge"
    t.boolean  "portalHyperTension"
    t.boolean  "cirrhosis"
    t.boolean  "ascitites"
    t.boolean  "varices"
    t.boolean  "shunt"
    t.boolean  "transplant"
    t.boolean  "labResults"
    t.string   "otherHistory"
    t.integer  "splenicSize"
    t.boolean  "splenicThrombus"
    t.float    "splenicVelocity"
    t.string   "splenicFlowDir"
    t.integer  "smvSize"
    t.boolean  "smvThrombus"
    t.float    "smvVelocity"
    t.string   "smvFlowDir"
    t.integer  "portalMainSize"
    t.boolean  "portalMainThrombus"
    t.float    "portalMainVelocity"
    t.string   "portalMainFlowDir"
    t.integer  "portalRightSize"
    t.boolean  "portalRightThrombus"
    t.float    "portalRightVelocity"
    t.string   "portalRightFlowDir"
    t.integer  "portalLeftSize"
    t.boolean  "portalLeftThrombus"
    t.float    "portalLeftVelocity"
    t.string   "portalLeftFlowDir"
    t.integer  "hepaticMainSize"
    t.boolean  "hepaticMainThrombus"
    t.float    "hepaticMainVelocity"
    t.string   "hepaticMainFlowDir"
    t.integer  "hepaticRightSize"
    t.boolean  "hepaticRightThrombus"
    t.float    "hepaticRightVelocity"
    t.string   "hepaticRightFlowDir"
    t.integer  "hepaticLeftSize"
    t.boolean  "hepaticLeftThrombus"
    t.float    "hepaticLeftVelocity"
    t.string   "hepaticLeftFlowDir"
    t.integer  "ivcSize"
    t.boolean  "ivcThrombus"
    t.float    "ivcVelocity"
    t.string   "ivcFlowDir"
    t.integer  "renalRightSize"
    t.boolean  "renalRightThrombus"
    t.float    "renalRightVelocity"
    t.string   "renalRightFlowDir"
    t.integer  "renalLeftSize"
    t.boolean  "renalLeftThrombus"
    t.float    "renalLeftVelocity"
    t.string   "renalLeftFlowDir"
    t.integer  "liverSize"
    t.boolean  "liverThrombus"
    t.float    "liverVelocity"
    t.string   "liverFlowDir"
    t.integer  "spleenSize"
    t.boolean  "spleenThrombus"
    t.float    "spleenVelocity"
    t.string   "spleenFlowDir"
    t.datetime "created_at",           null: false
    t.datetime "updated_at",           null: false
  end

  add_index "hepatic_forms", ["form_id"], name: "index_hepatic_forms_on_form_id"

  create_table "le_arterial_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.float    "ankleBPRight"
    t.float    "ankleBPLeft"
    t.boolean  "indications"
    t.boolean  "prevSurgery"
    t.boolean  "vascularDisease"
    t.boolean  "heartDisease"
    t.boolean  "smoking"
    t.boolean  "injury"
    t.boolean  "medications"
    t.string   "otherHistory"
    t.boolean  "claudication"
    t.boolean  "restPain"
    t.boolean  "ulcerations"
    t.boolean  "gangrene"
    t.string   "otherSymptoms"
    t.float    "abiRight"
    t.float    "abiLeft"
    t.float    "commFemoralProxRight"
    t.float    "commFemoralProxLeft"
    t.float    "commFemoralDistRight"
    t.float    "commFemoralDistLeft"
    t.float    "supFemoralProxRight"
    t.float    "supFemoralProxLeft"
    t.float    "supFemoralDistRight"
    t.float    "supFemoralDistLeft"
    t.float    "deepFemoralProxRight"
    t.float    "deepFemoralProxLeft"
    t.float    "deepFemoralDistRight"
    t.float    "deepFemoralDistLeft"
    t.float    "poplitealProxRight"
    t.float    "poplitealProxLeft"
    t.float    "poplitealDistRight"
    t.float    "poplitealDistLeft"
    t.float    "antTibialProxRight"
    t.float    "antTibialProxLeft"
    t.float    "antTibialDistRight"
    t.float    "antTibialDistLeft"
    t.float    "postTibialProxRight"
    t.float    "postTibialProxLeft"
    t.float    "postTibialDistRight"
    t.float    "postTibialDistLeft"
    t.float    "peronealProxRight"
    t.float    "peronealProxLeft"
    t.float    "peronealDistRight"
    t.float    "peronealDistLeft"
    t.float    "otherProxRight"
    t.float    "otherProxLeft"
    t.float    "otherDistRight"
    t.float    "otherDistLeft"
    t.datetime "created_at",           null: false
    t.datetime "updated_at",           null: false
  end

  add_index "le_arterial_forms", ["form_id"], name: "index_le_arterial_forms_on_form_id"

  create_table "le_venous_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.string   "admittingDX"
    t.boolean  "pulEmb"
    t.boolean  "dvt"
    t.string   "otherSurgery"
    t.boolean  "medications"
    t.boolean  "commFemoralRight"
    t.boolean  "commFemoralLeft"
    t.boolean  "commFemoralAcuteRight"
    t.boolean  "commFemoralAcuteLeft"
    t.boolean  "supFemoralRight"
    t.boolean  "supFemoralLeft"
    t.boolean  "supFemoralAcuteRight"
    t.boolean  "supFemoralAcuteLeft"
    t.boolean  "poplitealRight"
    t.boolean  "poplitealLeft"
    t.boolean  "poplitealAcuteRight"
    t.boolean  "poplitealAcuteLeft"
    t.boolean  "postTibialRight"
    t.boolean  "postTibialLeft"
    t.boolean  "postTibialAcuteRight"
    t.boolean  "postTibialAcuteLeft"
    t.boolean  "peronealRight"
    t.boolean  "peronealLeft"
    t.boolean  "peronealAcuteRight"
    t.boolean  "peronealAcuteLeft"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  add_index "le_venous_forms", ["form_id"], name: "index_le_venous_forms_on_form_id"

  create_table "mesenteric_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.boolean  "abdominPain"
    t.boolean  "weightLoss"
    t.boolean  "chronicDiarrhea"
    t.boolean  "bowellInfarction"
    t.string   "otherHistory"
    t.float    "aortaFastPSV"
    t.float    "aortaPostPSV"
    t.float    "aortaFastEDV"
    t.float    "aortaPostEDV"
    t.float    "aortaFastRI"
    t.float    "aortaPostRI"
    t.float    "celiacOriginFastPSV"
    t.float    "celiacOriginPostPSV"
    t.float    "celiacOriginFastEDV"
    t.float    "celiacOriginPostEDV"
    t.float    "celiacOriginFastRI"
    t.float    "celiacOriginPostRI"
    t.float    "celiacMidFastPSV"
    t.float    "celiacMidPostPSV"
    t.float    "celiacMidFastEDV"
    t.float    "celiacMidPostEDV"
    t.float    "celiacMidFastRI"
    t.float    "celiacMidPostRI"
    t.float    "smaOriginFastPSV"
    t.float    "smaOriginPostPSV"
    t.float    "smaOriginFastEDV"
    t.float    "smaOriginPostEDV"
    t.float    "smaOriginFastRI"
    t.float    "smaOriginPostRI"
    t.float    "smaMidFastPSV"
    t.float    "smaMidPostPSV"
    t.float    "smaMidFastEDV"
    t.float    "smaMidPostEDV"
    t.float    "smaMidFastRI"
    t.float    "smaMidPostRI"
    t.float    "smaDistalFastPSV"
    t.float    "smaDistalPostPSV"
    t.float    "smaDistalFastEDV"
    t.float    "smaDistalPostEDV"
    t.float    "smaDistalFastRI"
    t.float    "smaDistalPostRI"
    t.float    "hepaticFastPSV"
    t.float    "hepaticPostPSV"
    t.float    "hepaticFastEDV"
    t.float    "hepaticPostEDV"
    t.float    "hepaticFastRI"
    t.float    "hepaticPostRI"
    t.float    "splenicFastPSV"
    t.float    "splenicPostPSV"
    t.float    "splenicFastEDV"
    t.float    "splenicPostEDV"
    t.float    "splenicFastRI"
    t.float    "splenicPostRI"
    t.float    "imaFastPSV"
    t.float    "imaPostPSV"
    t.float    "imaFastEDV"
    t.float    "imaPostEDV"
    t.float    "imaFastRI"
    t.float    "imaPostRI"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
  end

  add_index "mesenteric_forms", ["form_id"], name: "index_mesenteric_forms_on_form_id"

  create_table "notes", force: :cascade do |t|
    t.string   "name"
    t.string   "content"
    t.integer  "technologists_id"
    t.integer  "forms_id"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
  end

  add_index "notes", ["forms_id"], name: "index_notes_on_forms_id"

  create_table "renal_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.boolean  "hypertension"
    t.boolean  "atherosclerosis"
    t.boolean  "renalStenosis"
    t.boolean  "renalFailure"
    t.boolean  "graft"
    t.boolean  "transplant"
    t.boolean  "thrombosis"
    t.boolean  "malignancy"
    t.string   "otherHistory"
    t.float    "arteryRightPSV"
    t.float    "arteryLeftPSV"
    t.float    "arteryRightEDV"
    t.float    "arteryLeftEDV"
    t.float    "arteryRightRI"
    t.float    "arteryLeftRI"
    t.float    "arteryRightAT"
    t.float    "arteryLeftAT"
    t.float    "arteryRightDS"
    t.float    "arteryLeftDS"
    t.float    "arteryRightRAR"
    t.float    "arteryLeftRAR"
    t.float    "aortaRightPSV"
    t.float    "aortaLeftPSV"
    t.float    "aortaRightEDV"
    t.float    "aortaLeftEDV"
    t.float    "aortaRightRI"
    t.float    "aortaLeftRI"
    t.float    "aortaRightAT"
    t.float    "aortaLeftAT"
    t.float    "aortaRightDS"
    t.float    "aortaLeftDS"
    t.float    "aortaRightRAR"
    t.float    "aortaLeftRAR"
    t.float    "renalAOrginRightPSV"
    t.float    "renalAOrginLeftPSV"
    t.float    "renalAOrginRightEDV"
    t.float    "renalAOrginLeftEDV"
    t.float    "renalAOrginRightRI"
    t.float    "renalAOrginLeftRI"
    t.float    "renalAOrginRightAT"
    t.float    "renalAOrginLeftAT"
    t.float    "renalAOrginRightDS"
    t.float    "renalAOrginLeftDS"
    t.float    "renalAOrginRightRAR"
    t.float    "renalAOrginLeftRAR"
    t.float    "renalAProxRightPSV"
    t.float    "renalAProxLeftPSV"
    t.float    "renalAProxRightEDV"
    t.float    "renalAProxLeftEDV"
    t.float    "renalAProxRightRI"
    t.float    "renalAProxLeftRI"
    t.float    "renalAProxRightAT"
    t.float    "renalAProxLeftAT"
    t.float    "renalAProxRightDS"
    t.float    "renalAProxLeftDS"
    t.float    "renalAProxRightRAR"
    t.float    "renalAProxLeftRAR"
    t.float    "renalAMidRightPSV"
    t.float    "renalAMidLeftPSV"
    t.float    "renalAMidRightEDV"
    t.float    "renalAMidLeftEDV"
    t.float    "renalAMidRightRI"
    t.float    "renalAMidLeftRI"
    t.float    "renalAMidRightAT"
    t.float    "renalAMidLeftAT"
    t.float    "renalAMidRightDS"
    t.float    "renalAMidLeftDS"
    t.float    "renalAMidRightRAR"
    t.float    "renalAMidLeftRAR"
    t.float    "renalADistRightPSV"
    t.float    "renalADistLeftPSV"
    t.float    "renalADistRightEDV"
    t.float    "renalADistLeftEDV"
    t.float    "renalADistRightRI"
    t.float    "renalADistLeftRI"
    t.float    "renalADistRightAT"
    t.float    "renalADistLeftAT"
    t.float    "renalADistRightDS"
    t.float    "renalADistLeftDS"
    t.float    "renalADistRightRAR"
    t.float    "renalADistLeftRAR"
    t.float    "parenchymaRightPSV"
    t.float    "parenchymaLeftPSV"
    t.float    "parenchymaRightEDV"
    t.float    "parenchymaLeftEDV"
    t.float    "parenchymaRightRI"
    t.float    "parenchymaLeftRI"
    t.float    "parenchymaRightAT"
    t.float    "parenchymaLeftAT"
    t.float    "parenchymaRightDS"
    t.float    "parenchymaLeftDS"
    t.float    "parenchymaRightRAR"
    t.float    "parenchymaLeftRAR"
    t.float    "interlobularRightPSV"
    t.float    "interlobularLeftPSV"
    t.float    "interlobularRightEDV"
    t.float    "interlobularLeftEDV"
    t.float    "interlobularRightRI"
    t.float    "interlobularLeftRI"
    t.float    "interlobularRightAT"
    t.float    "interlobularLeftAT"
    t.float    "interlobularRightDS"
    t.float    "interlobularLeftDS"
    t.float    "interlobularRightRAR"
    t.float    "interlobularLeftRAR"
    t.float    "arcuateRightPSV"
    t.float    "arcuateLeftPSV"
    t.float    "arcuateRightEDV"
    t.float    "arcuateLeftEDV"
    t.float    "arcuateRightRI"
    t.float    "arcuateLeftRI"
    t.float    "arcuateRightAT"
    t.float    "arcuateLeftAT"
    t.float    "arcuateRightDS"
    t.float    "arcuateLeftDS"
    t.float    "arcuateRightRAR"
    t.float    "arcuateLeftRAR"
    t.float    "renalVeinRightPSV"
    t.float    "renalVeinLeftPSV"
    t.float    "renalVeinRightEDV"
    t.float    "renalVeinLeftEDV"
    t.float    "renalVeinRightRI"
    t.float    "renalVeinLeftRI"
    t.float    "renalVeinRightAT"
    t.float    "renalVeinLeftAT"
    t.float    "renalVeinRightDS"
    t.float    "renalVeinLeftDS"
    t.float    "renalVeinRightRAR"
    t.float    "renalVeinLeftRAR"
    t.float    "renalSizeRightPSV"
    t.float    "renalSizeLeftPSV"
    t.float    "renalSizeRightEDV"
    t.float    "renalSizeLeftEDV"
    t.float    "renalSizeRightRI"
    t.float    "renalSizeLeftRI"
    t.float    "renalSizeRightAT"
    t.float    "renalSizeLeftAT"
    t.float    "renalSizeRightDS"
    t.float    "renalSizeLeftDS"
    t.float    "renalSizeRightRAR"
    t.float    "renalSizeLeftRAR"
    t.datetime "created_at",           null: false
    t.datetime "updated_at",           null: false
  end

  add_index "renal_forms", ["form_id"], name: "index_renal_forms_on_form_id"

  create_table "technologists", force: :cascade do |t|
    t.integer  "bruit_id"
    t.string   "firstname"
    t.string   "lastname"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "technologists", ["bruit_id"], name: "index_technologists_on_bruit_id"

  create_table "ue_arterial_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.boolean  "vasDisease"
    t.boolean  "smoking"
    t.boolean  "heartDisease"
    t.boolean  "meds"
    t.boolean  "injury"
    t.boolean  "prevSurgery"
    t.boolean  "diabetes"
    t.string   "otherHistory"
    t.boolean  "claudication"
    t.boolean  "numbness"
    t.boolean  "pain"
    t.boolean  "colorChange"
    t.string   "otherSymptoms"
    t.float    "subclavianPSVRight"
    t.float    "subclavianPSVLeft"
    t.float    "subclavianEDVRight"
    t.float    "subclavianEDVLeft"
    t.float    "axillaryPSVRight"
    t.float    "axillaryPSVLeft"
    t.float    "axillaryEDVRight"
    t.float    "axillaryEDVLeft"
    t.float    "brachialPSVRight"
    t.float    "brachialPSVLeft"
    t.float    "brachialEDVRight"
    t.float    "brachialEDVLeft"
    t.float    "radialPSVRight"
    t.float    "radialPSVLeft"
    t.float    "radialEDVRight"
    t.float    "radialEDVLeft"
    t.float    "ulnarPSVRight"
    t.float    "ulnarPSVLeft"
    t.float    "ulnarEDVRight"
    t.float    "ulnarEDVLeft"
    t.float    "palmarPSVRight"
    t.float    "palmarPSVLeft"
    t.float    "palmarEDVRight"
    t.float    "palmarEDVLeft"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
  end

  add_index "ue_arterial_forms", ["form_id"], name: "index_ue_arterial_forms_on_form_id"

  create_table "ue_venous_forms", force: :cascade do |t|
    t.integer  "form_id"
    t.boolean  "recentEvasiveProc"
    t.boolean  "recentAVFistula"
    t.string   "admittingDisease"
    t.boolean  "surgery"
    t.string   "otherSurgery"
    t.boolean  "diabetes"
    t.boolean  "myocardialInf"
    t.boolean  "conHeartFailure"
    t.string   "otherHistory"
    t.boolean  "pain"
    t.boolean  "numbness"
    t.boolean  "colorChange"
    t.string   "otherSymptoms"
    t.string   "subclavianWaveformRight"
    t.boolean  "subclavianCompressionRight"
    t.string   "subclavianWaveformLeft"
    t.boolean  "subclavianCompressionLeft"
    t.string   "axillaryWaveformRight"
    t.boolean  "axillaryCompressionRight"
    t.string   "axillaryWaveformLeft"
    t.boolean  "axillaryCompressionLeft"
    t.string   "brachialWaveformRight"
    t.boolean  "brachialCompressionRight"
    t.string   "brachialWaveformLeft"
    t.boolean  "brachialCompressionLeft"
    t.string   "radialWaveformRight"
    t.boolean  "radialCompressionRight"
    t.string   "radialWaveformLeft"
    t.boolean  "radialCompressionLeft"
    t.string   "ulnarWaveformRight"
    t.boolean  "ulnarCompressionRight"
    t.string   "ulnarWaveformLeft"
    t.boolean  "ulnarCompressionLeft"
    t.string   "basilicWaveformRight"
    t.boolean  "basilicCompressionRight"
    t.string   "basilicWaveformLeft"
    t.boolean  "basilicCompressionLeft"
    t.string   "cephalicWaveformRight"
    t.boolean  "cephalicCompressionRight"
    t.string   "cephalicWaveformLeft"
    t.boolean  "cephalicCompressionLeft"
    t.string   "medCubitalWaveformRight"
    t.boolean  "medCubitalCompressionRight"
    t.string   "medCubitalWaveformLeft"
    t.boolean  "medCubitalCompressionLeft"
    t.string   "intJugularWaveformRight"
    t.boolean  "intJugularCompressionRight"
    t.string   "intJugularWaveformLeft"
    t.boolean  "intJugularCompressionLeft"
    t.datetime "created_at",                 null: false
    t.datetime "updated_at",                 null: false
  end

  add_index "ue_venous_forms", ["form_id"], name: "index_ue_venous_forms_on_form_id"

  create_table "users", force: :cascade do |t|
    t.string   "firstname"
    t.string   "lastname"
    t.string   "email"
    t.string   "password_digest"
    t.datetime "created_at",                        null: false
    t.datetime "updated_at",                        null: false
    t.string   "activation_digest"
    t.string   "reset_digest"
    t.string   "username"
    t.boolean  "activated",         default: false
    t.string   "remember_digest"
  end

  create_table "waveforms", force: :cascade do |t|
    t.string   "venousFlow"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
