class CreateRenalForms < ActiveRecord::Migration
  def change
    create_table :renal_forms do |t|
      t.references :form, index: true, foreign_key: true
      t.boolean :hypertension
      t.boolean :atherosclerosis
      t.boolean :renalStenosis
      t.boolean :renalFailure
      t.boolean :graft
      t.boolean :transplant
      t.boolean :thrombosis
      t.boolean :malignancy
      t.string :otherHistory
      t.float :arteryRightPSV
      t.float :arteryLeftPSV
      t.float :arteryRightEDV
      t.float :arteryLeftEDV
      t.float :arteryRightRI
      t.float :arteryLeftRI
      t.float :arteryRightAT
      t.float :arteryLeftAT
      t.float :arteryRightDS
      t.float :arteryLeftDS
      t.float :arteryRightRAR
      t.float :arteryLeftRAR
      t.float :aortaRightPSV
      t.float :aortaLeftPSV
      t.float :aortaRightEDV
      t.float :aortaLeftEDV
      t.float :aortaRightRI
      t.float :aortaLeftRI
      t.float :aortaRightAT
      t.float :aortaLeftAT
      t.float :aortaRightDS
      t.float :aortaLeftDS
      t.float :aortaRightRAR
      t.float :aortaLeftRAR
      t.float :renalAOrginRightPSV
      t.float :renalAOrginLeftPSV
      t.float :renalAOrginRightEDV
      t.float :renalAOrginLeftEDV
      t.float :renalAOrginRightRI
      t.float :renalAOrginLeftRI
      t.float :renalAOrginRightAT
      t.float :renalAOrginLeftAT
      t.float :renalAOrginRightDS
      t.float :renalAOrginLeftDS
      t.float :renalAOrginRightRAR
      t.float :renalAOrginLeftRAR
      t.float :renalAProxRightPSV
      t.float :renalAProxLeftPSV
      t.float :renalAProxRightEDV
      t.float :renalAProxLeftEDV
      t.float :renalAProxRightRI
      t.float :renalAProxLeftRI
      t.float :renalAProxRightAT
      t.float :renalAProxLeftAT
      t.float :renalAProxRightDS
      t.float :renalAProxLeftDS
      t.float :renalAProxRightRAR
      t.float :renalAProxLeftRAR
      t.float :renalAMidRightPSV
      t.float :renalAMidLeftPSV
      t.float :renalAMidRightEDV
      t.float :renalAMidLeftEDV
      t.float :renalAMidRightRI
      t.float :renalAMidLeftRI
      t.float :renalAMidRightAT
      t.float :renalAMidLeftAT
      t.float :renalAMidRightDS
      t.float :renalAMidLeftDS
      t.float :renalAMidRightRAR
      t.float :renalAMidLeftRAR
      t.float :renalADistRightPSV
      t.float :renalADistLeftPSV
      t.float :renalADistRightEDV
      t.float :renalADistLeftEDV
      t.float :renalADistRightRI
      t.float :renalADistLeftRI
      t.float :renalADistRightAT
      t.float :renalADistLeftAT
      t.float :renalADistRightDS
      t.float :renalADistLeftDS
      t.float :renalADistRightRAR
      t.float :renalADistLeftRAR
      t.float :parenchymaRightPSV
      t.float :parenchymaLeftPSV
      t.float :parenchymaRightEDV
      t.float :parenchymaLeftEDV
      t.float :parenchymaRightRI
      t.float :parenchymaLeftRI
      t.float :parenchymaRightAT
      t.float :parenchymaLeftAT
      t.float :parenchymaRightDS
      t.float :parenchymaLeftDS
      t.float :parenchymaRightRAR
      t.float :parenchymaLeftRAR
      t.float :interlobularRightPSV
      t.float :interlobularLeftPSV
      t.float :interlobularRightEDV
      t.float :interlobularLeftEDV
      t.float :interlobularRightRI
      t.float :interlobularLeftRI
      t.float :interlobularRightAT
      t.float :interlobularLeftAT
      t.float :interlobularRightDS
      t.float :interlobularLeftDS
      t.float :interlobularRightRAR
      t.float :interlobularLeftRAR
      t.float :arcuateRightPSV
      t.float :arcuateLeftPSV
      t.float :arcuateRightEDV
      t.float :arcuateLeftEDV
      t.float :arcuateRightRI
      t.float :arcuateLeftRI
      t.float :arcuateRightAT
      t.float :arcuateLeftAT
      t.float :arcuateRightDS
      t.float :arcuateLeftDS
      t.float :arcuateRightRAR
      t.float :arcuateLeftRAR
      t.float :renalVeinRightPSV
      t.float :renalVeinLeftPSV
      t.float :renalVeinRightEDV
      t.float :renalVeinLeftEDV
      t.float :renalVeinRightRI
      t.float :renalVeinLeftRI
      t.float :renalVeinRightAT
      t.float :renalVeinLeftAT
      t.float :renalVeinRightDS
      t.float :renalVeinLeftDS
      t.float :renalVeinRightRAR
      t.float :renalVeinLeftRAR
      t.float :renalSizeRightPSV
      t.float :renalSizeLeftPSV
      t.float :renalSizeRightEDV
      t.float :renalSizeLeftEDV
      t.float :renalSizeRightRI
      t.float :renalSizeLeftRI
      t.float :renalSizeRightAT
      t.float :renalSizeLeftAT
      t.float :renalSizeRightDS
      t.float :renalSizeLeftDS
      t.float :renalSizeRightRAR
      t.float :renalSizeLeftRAR
      t.timestamps null: false
    end
  end
end
